language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer  # https://github.com/travis-ci/travis-ci/issues/3259
script:
  - cd $TRAVIS_BUILD_DIR && mvn package
env:
  global:
    - MAVEN_OPTS="-Xmx2g -Xms2g"
cache:
  directories:
  - $HOME/.m2
